apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: substratus-training-data-standard
allowVolumeExpansion: true
parameters:
  type: pd-balanced
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowedTopologies:
- matchLabelExpressions:
  - key: topology.gke.io/zone
    values:
    # TODO: Template this out or have the controller specify this.
    - us-central1-a

