# permissions for end users to view models.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: model-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: substratus
    app.kubernetes.io/part-of: substratus
    app.kubernetes.io/managed-by: kustomize
  name: model-viewer-role
rules:
  - apiGroups:
      - substratus.ai
    resources:
      - models
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - substratus.ai
    resources:
      - models/status
    verbs:
      - get
